In [2]:
import numpy as np

arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
type(arr[0])

numpy.int32

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.shape

(2, 3)

In [12]:
arr[0]

array([1, 2, 3])

In [13]:
arr[0][0]

1

In [14]:
arr[0][1]

2

In [15]:
arr = np.array([
    [0,1,2],
    [2,3,4],
    [3,4,5]
])
lst = [
    [0,1,2],
    [1,2,3],
    [3,4,5]
]

In [18]:
arr + 3

array([[3, 4, 5],
       [5, 6, 7],
       [6, 7, 8]])

In [19]:
arr

array([[0, 1, 2],
       [2, 3, 4],
       [3, 4, 5]])

In [20]:
lst * 3

[[0, 1, 2],
 [1, 2, 3],
 [3, 4, 5],
 [0, 1, 2],
 [1, 2, 3],
 [3, 4, 5],
 [0, 1, 2],
 [1, 2, 3],
 [3, 4, 5]]

In [21]:
lst

[[0, 1, 2], [1, 2, 3], [3, 4, 5]]

In [22]:
5 - arr

array([[5, 4, 3],
       [3, 2, 1],
       [2, 1, 0]])

In [23]:
5 - lst

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [25]:
arr = np.array([i for i in range(10)])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.arange(3,20,2)
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
arr = np.zeros((2,3), np.int32)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
arr.ndim

2

In [33]:
arr = np.zeros((4,3,2))
arr

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
arr = np.ones((4,3,2))
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [38]:
arr = np.random.rand(2,3)
arr

array([[0.56956392, 0.96724712, 0.03448278],
       [0.5871812 , 0.6113688 , 0.26671818]])

In [41]:
arr = np.arange(0,180,10).reshape(2,3,3)
arr

array([[[  0,  10,  20],
        [ 30,  40,  50],
        [ 60,  70,  80]],

       [[ 90, 100, 110],
        [120, 130, 140],
        [150, 160, 170]]])

In [43]:
1 * (arr < 100)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [44]:
arr < 100

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True, False, False],
        [False, False, False],
        [False, False, False]]])

In [46]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}

In [55]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [53]:
np.set_printoptions(threshold=1000)

In [54]:
np.get_printoptions()

{'edgeitems': 3,
 'threshold': 1000,
 'floatmode': 'maxprec',
 'precision': 8,
 'suppress': False,
 'linewidth': 75,
 'nanstr': 'nan',
 'infstr': 'inf',
 'sign': '-',
 'formatter': None,
 'legacy': False}